---
# tasks file for ocp-prepare-prereqs

- name: Install Required Packages
  tags: install_pkgs
  yum:
    name: "{{ packages }}"
    state: latest      
  vars:
    packages:
    - bind-chroot
    - tftp-server 
    - ipxe-bootimgs
    - dhcp-server
    - httpd
    - haproxy

- name: Define named.conf
  tags: conf_dns
  template:
    src: named.j2
    dest: /etc/named.conf
    owner: root
    group: root

- name: Define zone file
  tags: conf_dns
  template:
    src: dns-zone.j2
    dest: /var/named/{{zone_name}}.zone
    owner: root
    group: root

- name: Define reverse zone file
  tags: conf_dns
  template:
    src: dns-reverse-zone.j2
    dest: /var/named/{{reverse_zone_name}}.zone
    owner: root
    group: root

- name: Define dhcp conf file
  tags: conf_dhcp
  template:
    src: dhcp.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root

- name: Define haproxy conf file
  tags: conf_haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root    
